### ISSUE TITLE
Glycan "roots" do not show proper Chain ID after PDB remediation

### ISSUE THREAD

**Issue by glycojones** [glycojones/privateer#17]
Will need to download e.g. the remediated 5FJI from the PDB and check.

**Comment by GABRAH** [comment]
I think I found the reason why(although I'm not sure that this is the same issue): 

When privateer produces output.xml, I use the following: 
of_xml << "     <GlycanChain>"      << list_of_glycans[i].get_chain()                    << "</GlycanChain>\n"         ; 
to get weird chains like A0, B0 etc...

At the same time SVG file name is fine, and the reason for that is: 
std::string get_root_for_filename () { return "[" + get_chain().trim().substr(0,1) + "]-" + get_root().first.type().trim() + get_root().first.id().trim(); }

I need to fix my method by doing this instead:
of_xml << "     <GlycanChain>"      << list_of_glycans[i].get_chain().trim().substr(0,1)                   << "</GlycanChain>\n"         ; 


Unfortunately, this bug got pushed together with the next release of Privateer for CCP4... my bad. 


If this is not the same issue we are talking about, could you describe the issue in more detail?

**Comment by GABRAH** [comment]
Fixed. When potential_n/o/c/s_roots are searched, I replaced std::vector<clipper::MMonomer> to std::vector<std::pair<clipper::MMonomer, clipper::String>> potential_n_roots; in order to create a glycan object in the following way: clipper::MGlycan mg (   potential_n_roots[i].second,
                                            potential_n_roots[i].first,
                                            list_of_sugars.back(),
                                            this->expression_system );
