### ISSUE TITLE
Crash with 2LHX

### ISSUE THREAD

**Issue by glycojones** [glycojones/privateer#7]
Crash (segmentation fault 11) when processing 2LHX from the test dataset. 
Problem identified via pybind11 interface, master branch.
Harold suggests this is due to PDB remediation. Protein has o-glycans.

**Comment by GABRAH** [comment]
@glycojones 

This structure does not segfault after having re-downloaded it from PDB:
https://www.rcsb.org/structure/2LHX

Might be worthwhile re-downloading entire test dataset considering the carbohydrate remediation of PDB database in the summer.
